version: '3'

services:
  broker-service:
    build:
      context: ./broker
      dockerfile: ./broker.dockerfile

    restart: always
    ports:
      - "8001:8000"

    deploy:
      mode: replicated
      replicas: 1